### PR TITLE
Correcting grammatical mistakes in README.md

### PR DESCRIPTION
**Pull request by pm17**
README.md file should be error free

### CODE REVIEW

**Comment by littlestar642** [comment]
Please rebase your branch with the latest commit. I left that typo for you to rectify,at the same place. Keep Contributing

**Comment by littlestar642** [comment]
@pm17 Are you wroking on this?

**Comment by pm17** [comment]
@littlestar642  yes, my EXAMS ARE on so trying to manage

**Comment by littlestar642** [comment]
Closing because redundant

**Pull request closed without merging**
