### PR TITLE
feat: Navbar slide in on scroll

### LINKED ISSUE #89: make the navbar to slide in on scroll
Present behavior-:
The navbar is static and also having a bottom shadow.

Desired behaviour:-
Remove the bottom shadow on no scroll and make the navbar to slide in on scroll of 10 px. 
I guess we need the code for two navs and then we can toggle proper classes on scroll.

### PR DESCRIPTION
**Pull request by crisner**
Have added some placeholder text to blogDemo.hbs file to test feature on scroll. The feature is coded in **navfeature.js** and have added it to the script section of about, blog, and wall of fame demo pages.

Preview feature [here](https://crisner-udabuddy.herokuapp.com/blogDemo).

resolves #89

### CODE REVIEW

**Comment by littlestar642** [comment]
@crisner Why is there a delay of like 3 sec when the scroll position is reset to 0. Is that a known addition? If yes,then please help me understand its need.

**Comment by crisner** [comment]
I've set a delay for the nav to slide back out. It is a 6 second delay to give the user enough time to click on the links in the slider-navbar. I'm guessing the delay you meant is the time it takes for the slider-navbar to slide back out? It may seem like a 3sec delay when you scroll back to the top.

**Comment by crisner** [comment]
If that is not desired, I can make the navbar slide-in on scroll down and slide back out on scroll-up. This way, there wouldn't be a need for delay.@littlestar642

**Comment by littlestar642** [comment]
@crisner Well i guess a setinterval value of 6 sec can be reduced to some miliseconds. The delay appears slightly async from the normal page flow. A lesser delay would be more intutive for the user.

**Comment by littlestar642** [comment]
Also if you have a idea of why a 6 sec delay will be beneficial for a user,please help me understand.

**Comment by crisner** [comment]
When I was testing the feature with 4sec delay as a user casually browsing, the slider-nav would slide out just as I began to hover on the links. I figured it might be distracting to the user and increased the delay. That is the only reason. I initially thought that was fine though. I'll reduce the delay and update.

**Comment by crisner** [comment]
@littlestar642 Please check this [link](https://crisner-udabuddy.herokuapp.com/blogDemo) now. I have halved the delay.

**Comment by littlestar642** [comment]
@crisner please make that set interval value for less than 1 sec for now. As the event loop is already queued with check scroll function there i guess, getting a assurance of min 1 sec works here. Also a quick and not much delayed return of the nav will feel better

**Pull request merged**
