### PR TITLE
Added  background gradient  

### PR DESCRIPTION
**Pull request by vivek1996**

### CODE REVIEW

**Comment by vivek1996** [comment]
Added background gradient and changed the text color of heading

**Comment by littlestar642** [comment]
@vivek1996 Can you please provide me with a Codepen link or a heroku deployment so that i can see your changes?

**Comment by vivek1996** [comment]
@littlestar642  
capture

**Comment by littlestar642** [comment]
@vivek1996 This is too much design. The app looks colorful, which is not the real aim. From the mockups, you can get some primary and secondary colors and only use them instead of so many colors

**Comment by vivek1996** [comment]
@littlestar642  where I can find the mockup?

**Comment by littlestar642** [comment]
@vivek1996 There is a mockup on the issue section for this PR. You can refer that

**Pull request closed without merging**
