### PR TITLE
Changed the location of css folder.

### PR DESCRIPTION
**Pull request by V3dant**
The css file wasn't loading so changed the location of css folder. Also changed the directory of css folder in README.md.
error

### CODE REVIEW

**Comment by V3dant** [comment]
Okay but the css file isn't loading  what about it?

**Comment by littlestar642** [comment]
Please check in your html what path has been given to the css file and update that if it is not proper

**Comment by littlestar642** [comment]
Also update the changes in readme that you have done

**Comment by V3dant** [comment]
Okay

**Pull request closed without merging**
