### PR TITLE
[Added] Footer (Contact Us) Section. 

### PR DESCRIPTION
**Pull request by utkarsh2102**
This PR is in reference to #101.
The footer has been made as per the discussions on the issue.

CC: @littlestar642 @Prateek-Tewari

### CODE REVIEW

**Comment by Prateek-Tewari** [comment]
@utkarsh2102 can you post the screenshot as well?

**Comment by littlestar642** [comment]
@utkarsh2102 could you please provide a deployment or a CodePen. Also squash  your commits. Also if possible make a partial for the footer and then add it to the pages. That way it will be perfect

**Comment by littlestar642** [comment]
@utkarsh2102 Any ETA on this?

**Comment by littlestar642** [comment]
@utkarsh2102 Any ETA on this?

**Comment by utkarsh2102** [comment]
Hi @littlestar642 and @Prateek-Tewari,
Really sorry for the delay. I've made some changes and the codepen link is as follows:
https://codepen.io/utkarsh2102/pen/dewVLG
Once implemented with the other documents, the changes will look fine.

**Comment by littlestar642** [comment]
@utkarsh2102 Doesn't this looks slightly right offseted. I guess the concern should be to center things. Also i liked the idea of a mailing list,but m not sure that we will be having that in the app. Anyways, just center the layout,and brighten the text a little as it is not much legible on mobile screen

**Pull request closed without merging**
