### PR TITLE
Adding resources page and index.js file changed to listen to request

### PR DESCRIPTION
**Pull request by souro18**
https://codepen.io/souro18/project/full/AdbQQV/
have used some dummy images. Haven't added images in media folder.
#33

### CODE REVIEW

**Comment by littlestar642** [comment]
Great work @souro18 . I just wanted that if you could please add a dropdown in mobile view in the navbar the layout would look more complete then. Do that Asap and i would merge this pr. Keep contributing!

**Comment by souro18** [comment]
dropdown or sidenav?

**Comment by souro18** [comment]
sidenav added https://codepen.io/souro18/project/full/AdbQQV/ @littlestar642

**Comment by souro18** [comment]
Can I add icons in navbar?

**Comment by Prateek-Tewari** [comment]
@souro18 sure buddy,you can. Go ahead with the navbar icons.

**Comment by souro18** [comment]
icons added.please merge it .

**Comment by mepsrajput** [comment]
@souro18 can you please show, how it looks live?

**Comment by littlestar642** [comment]
@souro18 Please make a seperate js file for the resource page and then put there the script lines you wrote at the end.  Also squash your commits. I will merge it then.

**Pull request closed without merging**
