### PR TITLE
GitHub 22x22 PNG icon

### PR DESCRIPTION
**Pull request by pm17**
GitHub icon of 22x22 in PNG format

### CODE REVIEW

**Comment by pm17** [comment]
I have added the icon into the media folder in public and deleted the folder which I initially created in confusion

**Comment by mepsrajput** [comment]
Can you inbox me the image, i'll try it locally, if it works i'll merge your PR?

**Comment by pm17** [comment]
should I mail it to you now also?



-- 

Thanks & Regards,

Parvesh Mourya

**Comment by mepsrajput** [comment]
Yes you can mail me at viveksingh12126@gmail.com

**Pull request closed without merging**
