### PR TITLE
Modified index page

### PR DESCRIPTION
**Pull request by shreyag12**
Modified UI of index page

### CODE REVIEW

**Comment by shreyag12** [comment]
This is the screenshot of my index page .
screenshot from 2018-04-14 23-03-56

**Comment by littlestar642** [comment]
@shreyag12 We have used firebase and it abstractly provides signup and login both in one. We dont need that signup form next to the buttons. Please remove that

**Comment by littlestar642** [comment]
@shreyag12 I have made a new deployment. The concerns for the index page should be lowered now so that we can focus on other pages. You can still work on this page and make prs,but try working on other pages now.

**Comment by shreyag12** [comment]
Ok.

**Comment by littlestar642** [comment]
@shreyag12 Are you working on this?

**Comment by shreyag12** [comment]
@littlestar642  Yes. I will try to deploy it on heroku by today so that you guys can see it then will raise a PR .

**Comment by littlestar642** [comment]
@shreyag12 Any ETA on this?

**Comment by shreyag12** [comment]
@littlestar642 Yes been busy for few days. Deployment on heroku was not working.  Will try to deploy it on heroku and show it to you by today.

**Comment by littlestar642** [comment]
@shreyag12 If you have messed the project you can clone it again. Please bring your changes asap and if you are facing any difficulty then please inbox me

**Pull request closed without merging**
