### PR TITLE
fix: issue #109

### PR DESCRIPTION
**Pull request by skywalker212**

### CODE REVIEW

**Comment by littlestar642** [comment]
Can you give me a deployment. Also remove the description in your commit message

**Comment by skywalker212** [comment]
@littlestar642 wait, ill deploy and post the link here

**Comment by littlestar642** [comment]
@skywalker212 For no scroll, i.e 0 scroll length make the navbar background transparent. I guess that will look better for the present layout

**Comment by skywalker212** [comment]
@littlestar642 I have made the navbar transparent for 0 scroll, please look into the update and merge if possible.
heroku: https://quiet-savannah-78779.herokuapp.com/about

**Pull request merged**
