### PR TITLE
layout of about page

### PR DESCRIPTION
**Pull request by oreanroy**
layout of about page completed.

### CODE REVIEW

**Comment by littlestar642** [comment]
Can you please provide a deployment or a CodePen?

**Comment by oreanroy** [comment]
https://jsfiddle.net/8v5w1v4b/2/ have a look keep the output window of size of large screen

**Comment by littlestar642** [comment]
@oreanroy why are there two about.hbs files here. Also please squash your commits

**Comment by littlestar642** [comment]
Please squash your 4 commits to 1

**Pull request closed without merging**
